### ISSUE TITLE
Error on Prepare rig for Godot and strange deforms

### ISSUE THREAD

**Issue by BasilYes** [catprisbrey/Rigodotify#4]
Testing your addon (again) and get errors on new animals rigs, to recreate get my file and try to press Prepare rig for Godot on any animal.
https://drive.google.com/file/d/1X2mJvyYS9I7mOknQqWPvUroMp4LLT-6z/view?usp=sharing

and some issues with deforms bones on rigify simples (paw and spine in same file) may be intended
Deform before prepare to Godot
![image](https://github.com/catprisbrey/Rigodotify/assets/36816595/b80d8d5d-2e5b-4d62-8cc5-77566c092d63)
and after
![image](https://github.com/catprisbrey/Rigodotify/assets/36816595/bd0ec994-e34e-451d-acc8-79cfbfa8f9ab)

Paw before
![image](https://github.com/catprisbrey/Rigodotify/assets/36816595/24bf2409-7d81-465d-b266-5d3340f145cf)
Paw after
![image](https://github.com/catprisbrey/Rigodotify/assets/36816595/0c11c3e7-d362-4517-b9f6-a7aa1ec9fc1c)

**Comment by catprisbrey** [comment]
Sorry for the delays, had a game jam and then was out ill for a while, just didn't notice this ticket come in. I haven't been working on Rigodotify's animal parts in a while but i do remember having odd heel deforms during some tests, so this is likely the cause. A lot of what Rigodotify does is reduces and rearranges the more complex Rigify Rigs down to more basic bone setups, and rearranges their constraints. Seems like i may have misplaced which bones to rearranged in the heels of the paws. (likely i matched up something with the head and not the tail of the bone i wanted to adjust). So some of this wackiness is intented, but not likely to the extend of what you're seeing here. 

I'll dig into this soon and see about straightening it out.

**Comment by catprisbrey** [comment]
I may need more info since i'm struggling to reproduce this issue on a clean file of clean metarigs. Your file is a bit compromised to test on since there are so many metarigs and loose body parts about, that the Rigodotify tool won't know what which body it's looking at to properly clean things up. 

Here are the deform bones currently of the finalized Rigodotified rigs. Everything looks good here, so i'm unsure how you created the issue you shared.
![image](https://github.com/catprisbrey/Rigodotify/assets/43008564/fb3d3f20-0da3-49cc-9d00-7750a9cc88d1)


Which perhaps that offers some telling info to you? Rigodotify is quite simple, and it's not very clever. It's a focused tool on standardizing whole skeletons to a game dev standard. Not individual metasamples, or metarigs with a bunch of extra parts. Its scope is focused on standard bodies to game dev standards.  It expects/detects a whole skeleton type and cleans it up. No non-standard bodies or individual parts. No 5 legged dogs or 12 legged catbusses. That's not the scope of the project.

So perhaps that is what you were experiencing? A Rigodotify metarig, plus extra spine or paw samples added at that point, attempting to convert? If tha'ts the case, i'd recommend instead building the standard body first, and convert (that way normal body part animations should retarget in godot.  And then in a new object, build the custom non-standard body parts you need, generate that with just vanilla Rigify, and then parent that sub-rig setup to the Rigodotified rig as needed.
